### ISSUE TITLE
KeyVaultSecretReference not found when running CopyKeysSinglePass-Az.ps1

### ISSUE THREAD

**Issue by olileger** [AsrOneSdk/published-scripts#7] opened 2019-11-07 22:32 UTC
Hello

I'm having the following errors when running CopyKeysSinglePass-Az.ps1:

```
Au caractère XXXcopy-keys.ps1:245 : 6
+     [Microsoft.Azure.Management.Compute.Models.KeyVaultSecretReferenc ...
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Type [Microsoft.Azure.Management.Compute.Models.KeyVaultSecretReference] introuvable.
Au caractère XXXcopy-keys.ps1:250 : 6
+     [Microsoft.Azure.Management.Compute.Models.KeyVaultKeyReference]$ ...
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Type [Microsoft.Azure.Management.Compute.Models.KeyVaultKeyReference] introuvable.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TypeNotFound
```

Could you please help me ?
Thanks

Olivier

**Comment by punit1396** [comment] 2019-11-07 22:57
Manual workaround - Run Import-Module Az.Compute before running the script.
As for the script changes,
Uncomment and modify the required modules statement (line 26) to ensure Az.Compute is present in the current PS window context - #Requires -Modules Az.Compute

**Comment by punit1396** [comment] 2019-11-07 23:00
Closing issue as it's a duplicate of https://github.com/AsrOneSdk/published-scripts/issues/6

**Closed by punit1396** 2019-11-07 23:00 UTC
